import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabase"; // Đảm bảo đường dẫn này trỏ đúng vào file supabase.ts của bạn

export async function GET() {
  const dataToImport = [
    {
      name: "Đầu kéo Shacman X5000 6x4 400HP",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "6x4",
      engine_brand: "WEICHAI",
      engine_model: "WP10H",
      horsepower: 400,
      axle_type: "Cầu láp",
      gear_ratio: "4.111",
      other_config: null,
      price: 1150,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Shacman X5000 6x4 460HP",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "6x4",
      engine_brand: "WEICHAI",
      engine_model: "P12",
      horsepower: 460,
      axle_type: "Cầu láp",
      gear_ratio: "4.625",
      other_config: null,
      price: 1200,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Shacman X5000 6x4 460HP (WP10.5H)",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "6x4",
      engine_brand: "WEICHAI",
      engine_model: "WP10.5H",
      horsepower: 460,
      axle_type: "Cầu láp",
      gear_ratio: "4.111",
      other_config: null,
      price: 1200,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Shacman X5000 6x4 460HP (Cầu Dầu)",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "6x4",
      engine_brand: "WEICHAI",
      engine_model: "WP12",
      horsepower: 460,
      axle_type: "Cầu Dầu",
      gear_ratio: "5.262",
      other_config: null,
      price: 1220,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Shacman X5000 6x4 460HP (M10)",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "6x4",
      engine_brand: "CUMMINS",
      engine_model: "M10",
      horsepower: 460,
      axle_type: "Cầu láp",
      gear_ratio: "4.111/3.7",
      other_config: null,
      price: 1200,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Shacman X5000 6x4 460HP (Giường Đơn)",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "6x4",
      engine_brand: "CUMMINS",
      engine_model: "M10",
      horsepower: 460,
      axle_type: "Cầu láp",
      gear_ratio: "4.111",
      other_config: "Giường Đơn",
      price: 1190,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Shacman X5000 6x4 440HP",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "6x4",
      engine_brand: "CUMMINS",
      engine_model: "ISM11",
      horsepower: 440,
      axle_type: "Cầu láp",
      gear_ratio: "4.111",
      other_config: null,
      price: 1180,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Shacman X5000 6x4 440HP (Cầu Dầu)",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "6x4",
      engine_brand: "CUMMINS",
      engine_model: "ISM11",
      horsepower: 440,
      axle_type: "Cầu Dầu",
      gear_ratio: "5.262",
      other_config: null,
      price: 1210,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Shacman H3000S 6x4 460HP",
      category: "dau_keo",
      brand: "SHACMAN",
      cabin: "H3000S",
      drive_config: "6x4",
      engine_brand: "WEICHAI",
      engine_model: "WP12",
      horsepower: 460,
      axle_type: "Cầu Dầu",
      gear_ratio: "5.262",
      other_config: null,
      price: 1160,
      commission: 2.7,
    },
    {
      name: "Xe ben Shacman H3000S 8x4 340HP",
      category: "xe_ben",
      brand: "SHACMAN",
      cabin: "H3000S",
      drive_config: "8x4",
      engine_brand: "WEICHAI",
      engine_model: "P8",
      horsepower: 340,
      axle_type: "Cầu Dầu",
      gear_ratio: "5.262/4.769",
      other_config: "Thùng U",
      price: 1490,
      commission: 2.7,
    },
    {
      name: "Xe ben Shacman H3000S 8x4 400HP",
      category: "xe_ben",
      brand: "SHACMAN",
      cabin: "H3000S",
      drive_config: "8x4",
      engine_brand: "WEICHAI",
      engine_model: "WP10H",
      horsepower: 400,
      axle_type: "Cầu Dầu",
      gear_ratio: "4.769",
      other_config: "Thùng U",
      price: 1520,
      commission: 2.7,
    },
    {
      name: "Xe ben Shacman H3000S 8x4 385HP",
      category: "xe_ben",
      brand: "SHACMAN",
      cabin: "H3000S",
      drive_config: "8x4",
      engine_brand: "CUMMINS",
      engine_model: "M10",
      horsepower: 385,
      axle_type: "Cầu Dầu",
      gear_ratio: "4.769",
      other_config: "Thùng U",
      price: 1520,
      commission: 2.7,
    },
    {
      name: "Xe ben Shacman H3000S 6x4 385HP",
      category: "xe_ben",
      brand: "SHACMAN",
      cabin: "H3000S",
      drive_config: "6x4",
      engine_brand: "CUMMINS",
      engine_model: "M10",
      horsepower: 385,
      axle_type: "Cầu Dầu",
      gear_ratio: "5.262",
      other_config: "Thùng Vuông",
      price: 1440,
      commission: 2.7,
    },
    {
      name: "Xe ben Shacman X5000 8x4 400HP",
      category: "xe_ben",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "8x4",
      engine_brand: "WEICHAI",
      engine_model: "WP10H",
      horsepower: 400,
      axle_type: "Cầu Dầu",
      gear_ratio: "4.769",
      other_config: "Thùng U",
      price: 1540,
      commission: 2.7,
    },
    {
      name: "Xe ben Shacman X5000 8x4 400HP (Thùng Vuông)",
      category: "xe_ben",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "8x4",
      engine_brand: "WEICHAI",
      engine_model: "P12",
      horsepower: 400,
      axle_type: "Cầu Dầu",
      gear_ratio: "5.262",
      other_config: "Thùng Vuông",
      price: 1560,
      commission: 2.7,
    },
    {
      name: "Xe ben Shacman X5000 8x4 385HP",
      category: "xe_ben",
      brand: "SHACMAN",
      cabin: "X5000",
      drive_config: "8x4",
      engine_brand: "CUMMINS",
      engine_model: "M10",
      horsepower: 385,
      axle_type: "Cầu Dầu",
      gear_ratio: "4.769",
      other_config: "Thùng U",
      price: 1540,
      commission: 2.7,
    },
    {
      name: "Xe Trộn Shacman H3000S 6x4 340HP",
      category: "xe_tron",
      brand: "SHACMAN",
      cabin: "H3000S",
      drive_config: "6x4",
      engine_brand: "WEICHAI",
      engine_model: "P8",
      horsepower: 340,
      axle_type: "Cầu Dầu",
      gear_ratio: "5.262",
      other_config: "10m3",
      price: 1360,
      commission: 2.7,
    },
    {
      name: "Xe Trộn Shacman H3000S 6x4 360HP",
      category: "xe_tron",
      brand: "SHACMAN",
      cabin: "H3000S",
      drive_config: "6x4",
      engine_brand: "CUMMINS",
      engine_model: "M10",
      horsepower: 360,
      axle_type: "Cầu Dầu",
      gear_ratio: "4.769",
      other_config: "10m3",
      price: 1360,
      commission: 2.7,
    },
    {
      name: "Đầu kéo Đông Dương T7H 6x4 440HP (Cầu Dầu)",
      category: "dau_keo",
      brand: "ĐÔNG DƯƠNG",
      cabin: "T7H",
      drive_config: "6x4",
      engine_brand: "MAN",
      engine_model: "MC11",
      horsepower: 440,
      axle_type: "Cầu dầu",
      gear_ratio: "4.77",
      other_config: null,
      price: 1245,
      commission: 1.5,
    },
    {
      name: "Đầu kéo Đông Dương T7H 6x4 440HP (Cầu láp)",
      category: "dau_keo",
      brand: "ĐÔNG DƯƠNG",
      cabin: "T7H",
      drive_config: "6x4",
      engine_brand: "MAN",
      engine_model: "MC11",
      horsepower: 440,
      axle_type: "Cầu láp",
      gear_ratio: "4.11/3.7",
      other_config: null,
      price: 1290,
      commission: 1.5,
    },
    {
      name: "Xe ben Đông Dương 8x4 380HP (Thùng U)",
      category: "xe_ben",
      brand: "ĐÔNG DƯƠNG",
      cabin: null,
      drive_config: "8x4",
      engine_brand: null,
      engine_model: "D10",
      horsepower: 380,
      axle_type: null,
      gear_ratio: null,
      other_config: "Thùng U",
      price: 1555,
      commission: 1.5,
    },
    {
      name: "Xe ben Đông Dương 8x4 380HP (Thùng Vuông)",
      category: "xe_ben",
      brand: "ĐÔNG DƯƠNG",
      cabin: null,
      drive_config: "8x4",
      engine_brand: null,
      engine_model: "D10",
      horsepower: 380,
      axle_type: null,
      gear_ratio: null,
      other_config: "Thùng Vuông",
      price: 1615,
      commission: 1.5,
    },
    {
      name: "Xe ben Đông Dương 6x4 380HP (Thùng Vuông)",
      category: "xe_ben",
      brand: "ĐÔNG DƯƠNG",
      cabin: null,
      drive_config: "6x4",
      engine_brand: null,
      engine_model: "D10",
      horsepower: 380,
      axle_type: null,
      gear_ratio: null,
      other_config: "Thùng Vuông",
      price: 1500,
      commission: 1.5,
    },
    {
      name: "Đầu kéo Trí Mới T7H-MAX 6x4 460HP (Cầu Dầu)",
      category: "dau_keo",
      brand: "TRÍ MỚI",
      cabin: "T7H- MAX",
      drive_config: "6x4",
      engine_brand: "MAN",
      engine_model: "MC11",
      horsepower: 460,
      axle_type: "Cầu Dầu",
      gear_ratio: "4.77",
      other_config: null,
      price: 1315,
      commission: 1.5,
    },
    {
      name: "Đầu kéo Trí Mới T7H-MAX 6x4 460HP (Cầu láp)",
      category: "dau_keo",
      brand: "TRÍ MỚI",
      cabin: "T7H- MAX",
      drive_config: "6x4",
      engine_brand: "MAN",
      engine_model: "MC11",
      horsepower: 460,
      axle_type: "Cầu láp",
      gear_ratio: "4.11/3.7",
      other_config: null,
      price: 1375,
      commission: 1.5,
    },
  ];
  try {
    const { error } = await supabase
      .from("commercial_vehicles")
      .insert(dataToImport);

    if (error) {
      console.error("Lỗi từ Supabase:", error);
      return NextResponse.json(
        { success: false, error: error.message },
        { status: 500 },
      );
    }

    return NextResponse.json({
      success: true,
      message: `Đã thực sự import thành công ${dataToImport.length} sản phẩm vào Database!`,
    });
  } catch (err) {
    return NextResponse.json(
      { success: false, error: "Lỗi server" },
      { status: 500 },
    );
  }
}
